main: ${project.group}.helloworldplugin.HelloWorldPlugin
name: ${project.archivesBaseName}
version: ${project.version}

description: Practice plugin using Gradle and PaperAPI
api-version: 1.16
author: Zinadine Muñoz
